table:
  name: calculator_values_type
  schema: public
array_relationships:
  - name: calculator_values
    using:
      foreign_key_constraint_on:
        column: type
        table:
          name: calculator_values
          schema: public
select_permissions:
  - role: anonymous
    permission:
      columns:
        - value
        - description
      filter: {}
